ДЗ 4
Otus-DevOps-2023-09/batala_infra pull request #4
Opened 2023-11-05 22:29 UTC by batala

Домашнее задание
Деплой тестового приложениā
сделал 3 скрипта

2023-11-06 11:22 UTC, mrgreyves requested changes
Здравствуйте!)
![image](https://github.com/Otus-DevOps-2023-09/batala_infra/assets/34331259/9897e507-3db8-4480-be9f-4d4582b3d348)
У вас отсутствуют тесты =(
Мы добавляли Github Actions несколькими дз ранее
Вам нужно видимо подмержить изменения
В принципе ничего страшного, но починить надо
ДЗ возвращаю на доработку

2023-11-06 17:43 UTC, batala commented
Как я могу смержить изменения при не прохождении тестов на предыдущем дз?

2023-11-06 17:50 UTC, batala commented
у меня в дз 3 не срабатывает проверка я там написал что все сделал правильно и почему она не срабатывает не знаю
цитирую
× vpn: Check OpenVPN connection to pritunl (3 failed)
× Processes openvpn should exist
expected Processes openvpn to exist
× File /tmp/vpn-up should exist
expected File /tmp/vpn-up to exist
✔ Host 158.160.120.23 port 443 proto tcp should be reachable
× Host 10.128.0.28 port 22 proto tcp should be reachable

Я не понимаю что неправильно хост 10.128.0.28 доступен по порту 9999 я его так отфорвардил
командами
ssh -i c:/Users/AntBtk/.ssh/id_ed25519 -L 127.0.0.1:9999:10.128.0.28:22 appuser@158.160.120.23

pritunl тоже нормально работает
appuser@bastion:~$ ps -ef | grep pritunl
root 19928 1 0 Oct30 ? 01:14:32 /usr/lib/pritunl/usr/bin/python3 /usr/lib/pritunl/usr/bin/pritunl start
root 22652 19928 0 Oct31 ? 00:00:15 pritunl-web
root 24404 19928 0 Oct31 ? 00:09:36 openvpn /tmp/pritunl_36a17349c5bf4e7d9eae81db3470f168/8f4d51eeadb144b2aac7fa1df2a8d0ac/openvpn.conf
appuser 351381 351340 0 17:48 pts/2 00:00:00 grep --color=auto pritunl

2023-11-06 17:51 UTC, batala commented
я просто из-за это не могу вм удалить они мне весь грант уже съели, что мне нужно подмержить?

2023-11-06 17:52 UTC, batala commented
напишите где я ошибся, у меня нет времени пробиваться через тесты

2023-11-10 09:24 UTC, mrgreyves approved these changes
Здравствуйте!
Кажется что все починили
Наверное на момент проверки последней вы выключили вм
Код верен, дз принимаю

2023-11-10 11:11 UTC, merged